spacing = 2
padding = 1
hide_ascii = true
separator = ""
key_color = "#FF00FF"
separator_color = "White"

[palette]
glyph = "   "
type = "Light"
visible = true

[box]
title = " Macchina "
border = "rounded"
visible = true

[box.inner_margin]
x = 2
y = 1

[randomize]
key_color = false
separator_color = false

[keys]
kernel = ""
de = ""
distro = ""
terminal = ""
shell = "󱆃"
packages = ""
uptime = "󰥔"
memory = "󰍛"
resolution = "󰨇"
cpu = ""
gpu = ""
disk_space = ""
