require("core/options")
require("core/autocommands")
require("core/keymappings")
require("core/colorscheme")

require("packer_init")

require("plugins/impatient")
require("plugins/cmp")
require("plugins/lsp")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/comment")
require("plugins/indent")
require("plugins/autopairs")
require("plugins/gitsigns")
require("plugins/nvim-tree")
require("plugins/bufferline")
require("plugins/statusline")
require("plugins/neoscroll")
require("plugins/which-key")
require("plugins/alpha")
