require("core/options")
require("core/autocommands")
require("core/keymappings")

require("packer_init")
require("plugins/notify")

require("core/colorscheme")

require("plugins/impatient")
require("plugins/cmp")
require("plugins/lsp")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/dressing")
require("plugins/comment")
require("plugins/indent")
require("plugins/surround")
require("plugins/autopairs")
require("plugins/gitsigns")
require("plugins/nvim_tree")
require("plugins/symbol_outline")
require("plugins/fidget")
require("plugins/inc_rename")
require("plugins/bufferline")
require("plugins/lualine")
require("plugins/neoscroll")
require("plugins/which_key")
require("plugins/colorizer")
require("plugins/alpha")
