dev_comments = false
skip_readme = false

[hunspell]
lang = "en_GB"
search_dirs = ["./"]
skip_os_lookups = false
use_builtin = true
tokenization_splitchars = "\",;:.!?#(){}[]|/_-‒'`&@§¶…"
extra_dictionaries = [ "spellcheck.dic" ]

[hunspell.quirks]
transform_regex = []
allow_concatenation = false
allow_dashes = false
allow_emojis = true

[nlprules]

[reflow]
max_line_length = 100
