#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
cwd = { fg = "white" }
# Hovered
# hovered = { fg = "white", bg = "magenta" }
# preview_hovered = { fg = "magenta", underline = true }
# Find
find_keyword = { fg = "yellow", italic = true }
find_position = { fg = "white", italic = true }
# Marker
marker_copied = { fg = "lightyellow" }
marker_cut = { fg = "lightred" }
marker_marked = { fg = "magenta" }
marker_selected = { fg = "blue" }
# Count
count_copied = { fg = "black", bg = "yellow" }
count_cut = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "magenta" }
# Border
border_symbol = "│"
border_style = { fg = "white" }

symlink_target = { italic = true }
# Offset
# folder_offset = [1, 0, 1, 0]
# preview_offset = [1, 1, 1, 1]

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "white" }
progress_error = { fg = "red" }
# Permissions
perm_sep = { fg = "darkgray" }
perm_type = { fg = "lightgreen" }
perm_read = { fg = "lightyellow" }
perm_write = { fg = "lightred" }
perm_exec = { fg = "lightcyan" }

[mode]
normal_main = { fg = "white", bg = "magenta", bold = true }
normal_alt = { fg = "blue", bg = "gray", bold = true }
select_main = { fg = "white", bg = "magenta", bold = true }
select_alt = { fg = "red", bg = "gray" }
unset_main = { fg = "white", bg = "magenta", bold = true }
unset_alt = { fg = "red", bg = "gray" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "", close = "" }

# Tab
[tabs]
active = { fg = "white", bg = "magenta" }
inactive = { fg = "white", bg = "darkgray" }

[select]
border = { fg = "blue" }
active = { fg = "magenta" }
inactive = {}

[input]
border = { fg = "white" }
title = {}
value = {}
selected = { reversed = true }

[cmp]
border = { fg = "blue" }
active = { bg = "darkgray" }
inactive = {}
icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "blue" }
title = {}
hovered = { underline = true }

[which]
mask = {}
cand = { fg = "lightcyan" }
rest = { fg = "darkgray" }
desc = { fg = "white" }
separator = "  "
separator_style = { fg = "darkgray" }

[help]
on = { fg = "magenta" }
run = { fg = "cyan" }
desc = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer = { fg = "black", bg = "white" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "cyan" },
  # Videos
  { mime = "video/*", fg = "yellow" },
  { mime = "audio/*", fg = "yellow" },
  # Archives
  { mime = "application/zip", fg = "magenta" },
  { mime = "application/gzip", fg = "magenta" },
  { mime = "application/x-tar", fg = "magenta" },
  { mime = "application/x-bzip", fg = "magenta" },
  { mime = "application/x-bzip2", fg = "magenta" },
  { mime = "application/x-7z-compressed", fg = "magenta" },
  { mime = "application/x-rar", fg = "magenta" },
  { mime = "application/xz", fg = "magenta" },
  # Documents
  { mime = "application/doc", fg = "green" },
  { mime = "application/pdf", fg = "green" },
  { mime = "application/rtf", fg = "green" },
  { mime = "application/vnd.*", fg = "green" },
  # Fallback
  { url = "*/", fg = "blue" },
]

[icon]
# globs = {}

dirs = [
  { name = "Desktop", text = "" },
  { name = "Documents", text = "" },
  { name = "Downloads", text = "󰇚" },
  { name = "Library", text = "" },
  { name = "Music", text = "" },
  { name = "Pictures", text = "" },
  { name = "Videos", text = "" },
  { name = "Games", text = "󰖺" },
  { name = "repos", text = "" },
  { name = ".config", text = "" },
  { name = "work", text = "" },
  { name = ".git", text = "" },
  { name = "node_modules", text = "󰎙" },
  { name = "src", text = "" },
  { name = "build", text = "󱌢" },
  { name = "target", text = "󱌢" },
]
files = [
  { name = ".zshenv", text = "" },
  { name = "Containerfile", text = "󰡨" },
  { name = "Dockerfile", text = "󰡨" },
  { name = ".gitignore", text = "" },
  { name = ".gitmodules", text = "" },
  { name = ".gitattributes", text = "" },
]
globs = [
  { url = "zsh_*", text = "" },
  { url = ".*profile", text = "" },
  { url = ".*rc", text = "" },
  { url = "COPYING", text = "󰿃" },
  { url = "LICENSE", text = "󰿃" },
]
exts = [
  { name = "conf", text = "" },
  { name = "env", text = "" },
  { name = "ini", text = "" },
  { name = "txt", text = "" },
  { name = "md", text = "" },
  { name = "rst", text = "" },
  { name = "zip", text = "" },
  { name = "tar", text = "" },
  { name = "gz", text = "" },
  { name = "7z", text = "" },
  { name = "bz2", text = "" },
  { name = "xz", text = "" },
  { name = "csv", text = "" },
  { name = "doc", text = "" },
  { name = "doct", text = "" },
  { name = "docx", text = "" },
  { name = "dot", text = "" },
  { name = "ods", text = "" },
  { name = "ots", text = "" },
  { name = "pdf", text = "" },
  { name = "pom", text = "" },
  { name = "pot", text = "" },
  { name = "ppm", text = "" },
  { name = "pps", text = "" },
  { name = "ppt", text = "" },
  { name = "potx", text = "" },
  { name = "ppmx", text = "" },
  { name = "ppsx", text = "" },
  { name = "pptx", text = "" },
  { name = "xlc", text = "" },
  { name = "xlm", text = "" },
  { name = "xls", text = "" },
  { name = "xlt", text = "" },
  { name = "xlsm", text = "" },
  { name = "xlsx", text = "" },
  { name = "mp3", text = "" },
  { name = "flac", text = "" },
  { name = "wav", text = "" },
  { name = "aac", text = "" },
  { name = "ogg", text = "" },
  { name = "m4a", text = "" },
  { name = "mp2", text = "" },
  { name = "mp4", text = "" },
  { name = "mkv", text = "" },
  { name = "avi", text = "" },
  { name = "mov", text = "" },
  { name = "webm", text = "" },
  { name = "jpg", text = "" },
  { name = "jpeg", text = "" },
  { name = "png", text = "" },
  { name = "gif", text = "" },
  { name = "webp", text = "" },
  { name = "avif", text = "" },
  { name = "bmp", text = "" },
  { name = "ico", text = "" },
  { name = "svg", text = "" },
  { name = "xcf", text = "" },
  { name = "HEIC", text = "" },
  { name = "c", text = "" },
  { name = "cpp", text = "" },
  { name = "h", text = "" },
  { name = "hpp", text = "" },
  { name = "rs", text = "" },
  { name = "go", text = "" },
  { name = "py", text = "" },
  { name = "js", text = "" },
  { name = "ts", text = "" },
  { name = "tsx", text = "" },
  { name = "jsx", text = "" },
  { name = "rb", text = "" },
  { name = "php", text = "" },
  { name = "java", text = "" },
  { name = "sh", text = "" },
  { name = "fish", text = "" },
  { name = "swift", text = "" },
  { name = "vim", text = "" },
  { name = "lua", text = "" },
  { name = "html", text = "" },
  { name = "css", text = "" },
  { name = "scss", text = "" },
  { name = "json", text = "" },
  { name = "yml", text = "" },
  { name = "yaml", text = "" },
  { name = "lock", text = "" },
  { name = "nix", text = "" },
  { name = "bin", text = "" },
  { name = "exe", text = "" },
  { name = "pkg", text = "" },
]
