[manager]
cwd = { fg = "white" }

# Hovered
hovered = { fg = "white", bg = "magenta" }
preview_hovered = { fg = "magenta", underline = true }

# Find
find_keyword = { fg = "yellow", italic = true }
find_position = { fg = "white", italic = true }

# Marker
marker_copied   = { fg = "lightyellow" }
marker_cut      = { fg = "lightred" }
marker_marked   = { fg = "magenta" }
marker_selected = { fg = "blue" }

# Tab
tab_active = { fg = "white", bg = "magenta" }
tab_inactive = { fg = "white", bg = "darkgray" }
tab_width = 1

# Count
count_copied   = { fg = "black", bg = "yellow" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "magenta" }

# Border
border_symbol = "│"
border_style = { fg = "white" }

# Offset
folder_offset = [1, 0, 1, 0]
preview_offset = [1, 1, 1, 1]

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "magenta", bg = "reset" }

# Mode
mode_normal = { fg = "white", bg = "magenta", bold = true }
mode_select = { fg = "white", bg = "magenta", bold = true }
mode_unset = { fg = "white", bg = "magenta", bold = true }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "white" }
progress_error = { fg = "red" }

# Permissions
permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }

[select]
border = { fg = "blue" }
active = { fg = "magenta" }
inactive = {}

[input]
border = { fg = "white" }
title = {}
value = {}
selected = { reversed = true }

[cmp]
border = { fg = "blue" }
active = { bg = "darkgray" }
inactive = {}

icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "blue" }
title = {}
hovered = { underline = true }

[which]
mask = {}
cand = { fg = "lightcyan" }
rest = { fg = "darkgray" }
desc = { fg = "white" }
separator = "  "
separator_style = { fg = "darkgray" }

[help]
on = { fg = "magenta" }
exec = { fg = "cyan" }
desc = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer = { fg = "black", bg = "white" }

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "cyan" },

  # Videos
  { mime = "video/*", fg = "yellow" },
  { mime = "audio/*", fg = "yellow" },

  # Archives
  { mime = "application/zip", fg = "magenta" },
  { mime = "application/gzip", fg = "magenta" },
  { mime = "application/x-tar", fg = "magenta" },
  { mime = "application/x-bzip", fg = "magenta" },
  { mime = "application/x-bzip2", fg = "magenta" },
  { mime = "application/x-7z-compressed", fg = "magenta" },
  { mime = "application/x-rar", fg = "magenta" },
  { mime = "application/xz", fg = "magenta" },

  # Documents
  { mime = "application/doc", fg = "green" },
  { mime = "application/pdf", fg = "green" },
  { mime = "application/rtf", fg = "green" },
  { mime = "application/vnd.*", fg = "green" },

  # Fallback
  { name = "*/", fg = "blue" },
]

[icons]

"Desktop/" = ""
"Documents/" = ""
"Downloads/" = "󰇚"
"Library/" = ""
"Music/" = ""
"Pictures/" = ""
"Videos/" = ""
"Games/" = "󰖺"
"repos/" = ""
".config/" = ""
"work/" = ""

# Git
".git/" = ""
".gitignore" = ""
".gitmodules" = ""
".gitattributes" = ""

# Config files
".zshenv" = ""
"zsh_*" = ""
".*profile" = ""
".*rc" = ""
"*.conf" = ""
"*.env" = ""
"*.toml" = ""
"*.ini" = ""

# Text
"*.txt" = ""
"*.md" = ""
"*.rst" = ""
COPYING = "󰿃"
LICENSE = "󰿃"

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz" = ""
"*.7z" = ""
"*.bz2" = ""
"*.xz" = ""

# Documents
"*.csv" = ""
"*.doc" = ""
"*.doct" = ""
"*.docx" = ""
"*.dot" = ""
"*.ods" = ""
"*.ots" = ""
"*.pdf" = ""
"*.pom" = ""
"*.pot" = ""
"*.ppm" = ""
"*.pps" = ""
"*.ppt" = ""
"*.potx" = ""
"*.ppmx" = ""
"*.ppsx" = ""
"*.pptx" = ""
"*.xlc" = ""
"*.xlm" = ""
"*.xls" = ""
"*.xlt" = ""
"*.xlsm" = ""
"*.xlsx" = ""

# Audio
"*.mp3" = ""
"*.flac" = ""
"*.wav" = ""
"*.aac" = ""
"*.ogg" = ""
"*.m4a" = ""
"*.mp2" = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""
"*.webm" = ""

# Images
"*.jpg" = ""
"*.jpeg" = ""
"*.png" = ""
"*.gif" = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp" = ""
"*.ico" = ""
"*.svg" = ""
"*.xcf" = ""
"*.HEIC" = ""

# Programming
"*.c" = ""
"*.cpp" = ""
"*.h" = ""
"*.hpp" = ""
"*.rs" = ""
"*.go" = ""
"*.py" = ""
"*.js" = ""
"*.ts" = ""
"*.tsx" = ""
"*.jsx" = ""
"*.rb" = ""
"*.php" = ""
"*.java" = ""
"*.sh" = ""
"*.fish" = ""
"*.swift" = ""
"*.vim" = ""
"*.lua" = ""
"*.html" = ""
"*.css" = ""
"*.scss" = ""
"*.json" = ""
"*.yml" = ""
"*.yaml" = ""
"*.lock" = ""
"*.nix" = ""
Containerfile = "󰡨"
Dockerfile = "󰡨"
"node_modules/" = "󰎙"
"src/" = ""
"build/" = "󱌢"
"target/" = "󱌢"

# Misc
"*.bin" = ""
"*.exe" = ""
"*.pkg" = ""

# Default
"*" = ""
"*/" = ""
