#!/usr/bin/env bash
# requirements: rofi steam 
# required env variables: $ROFI_SCRIPTS_DIR $XDG_DATA_HOME

export SCRIPTS_DIR="$HOME/.config/rofi/scripts"

pushd "$ROFI_SCRIPTS_DIR" > /dev/null || exit

case "$1" in
    #selector: rofi -theme selecter -dmenu";;
    run)        rofi -show run -theme launcher;;
    clipboard)  rofi -modi "clipboard:greenclip print" -show clipboard -theme selector;;
    games)
        ./update-game-entries.sh -q

        (
            rofi -show drun -theme games -drun-categories SteamLibrary \
                -cache-dir "$XDG_DATA_HOME"
        )
        ;;
    *)  echo "Usage: $0 {run,games}"
;; esac

popd > /dev/null || exit
