#!/usr/bin/env bash
# requirements: rofi steam greenclip
# required env variables: $ROFI_SCRIPTS_DIR $XDG_DATA_HOME

case "$1" in
    run) rofi -show run -theme launcher ;;
    clipboard) rofi -modi "clipboard:greenclip print" -show clipboard -theme selector ;;
    fonts) fc-list | awk -F ":" '{print $2}' | rofi -dmenu | xclip -selection clipboard ;;
    games)
        "$ROFI_SCRIPTS"/update-game-entries.sh -q
        rofi -show drun -theme games -drun-categories SteamLibrary
        ;;
    sound_sink) pactl list short sinks | awk '{print $2}' | rofi -dmenu -theme selector -p "Select default sound sink" | pactl set-default-sink ;;
    *)
        echo "Usage: $0 {run,clipboard,fonts,games,sound_sink}"
        ;;
esac
