return {
    kind = {
        Text = "󰉿",
        Method = "m",
        Function = "󰊕",
        Constructor = "",
        Field = "",
        Variable = "󰆧",
        Class = "󰌗",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "󰎠",
        Enum = "",
        Keyword = "󰌋",
        Snippet = "",
        Color = "󰏘",
        File = "󰈙",
        Reference = "",
        Folder = "󰉋",
        EnumMember = "",
        Constant = "󰇽",
        Struct = "",
        Event = "",
        Operator = "󰆕",
        TypeParameter = "󰊄",
    },
    type = {
        Array = "󰅨",
        Number = "",
        String = "󰉿",
        Boolean = "𝐁",
        Object = "󰅩",
    },
    gitsigns = {
        AddOrChange = "▎",
        Delete = "󰐊",
    },
    ui = {
        ArrowClosed = "",
        ArrowOpen = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        HalfCircleLeft = "",
        HalfCircleRight = "",
        Search = "󰍉",
        Lightbulb = "󰌵",
        Bug = "",
        Code = "",
        Telescope = "",
        Selection = "",
        Package = "",
        List = "",
        Check = "",
        Next = "➜",
        Note = "󰎞",
        BookMark = "",
        ChevronRight = "",
        Table = "",
    },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "󰌵",
    },
    misc = {
        Next = "»",
        Plus = "+",
    },
}
