local constants = require("core.constants")
local o = vim.opt

o.backup = false -- stops creation of a backup file
o.cmdheight = 0 -- minimal command line, only show when needed
o.completeopt = { "menuone", "noselect", "noinsert" } -- mostly just for cmp
o.conceallevel = 2 -- concealing fluff in markdown
o.fileencoding = "utf-8" -- the encoding written to a file
o.hlsearch = false -- highlight all matches on previous search pattern
o.mouse = "a" -- allow the mouse to be used in neovim
o.pumheight = 10 -- pop up menu height
o.showmode = false -- we don't need to see things like -- INSERT -- anymore
o.showtabline = 2 -- always show tabs
o.ignorecase = true -- ignore case in search patterns
o.smartcase = true -- with ignorecase, means case sensitive search if a capital is used
o.splitbelow = true -- force all horizontal splits to go below current window
o.splitright = true -- force all vertical splits to go to the right of current window
o.swapfile = false -- creates a swapfile
o.termguicolors = true -- set term gui colours (most terminals support this)
o.timeoutlen = 50 -- time to wait for a mapped sequence to complete (in milliseconds)
o.undofile = true -- save undo history
o.undodir = vim.fn.stdpath("data") .. "/undodir" -- where to store undo history files
o.updatetime = 750 -- milliseconds idle until swap file is written to disk - some plugins' refresh times depend on this (4000 default)
o.backup = false -- don't keep permanent backup files
o.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
o.expandtab = true -- convert tabs to spaces
o.shiftwidth = constants.INDENT_SIZE -- the number of spaces inserted for each indentation
o.tabstop = constants.INDENT_SIZE -- insert x spaces for a tab
o.smartindent = true -- smart indenting when starting a new line
o.cursorline = true -- highlight the current line
o.number = true -- set numbered lines
o.relativenumber = true -- set relative numbered lines
o.numberwidth = 4 -- number column width
o.signcolumn = "yes" -- always show the sign column, otherwise it would shift the text each time
o.colorcolumn = constants.LINE_LENGTH -- coloured column will be drawn this many characters into a line
o.scrolloff = 10 -- visible section will move when cursor is this many lines away from the edge of the viewport
o.hidden = true -- buffer remains open in background after being closed
o.incsearch = true -- highlight search pattern in real time
o.inccommand = "split" -- show result of commands in real time
o.linebreak = true -- breaks lines only at characters in "breakat" ( ^I!@*-+;:,./?)
o.fillchars = "eob: " -- replaces ~ symbols with white space characters at the end of buffer
o.whichwrap = "<>[]hl" -- set which left->right navigations can also move cursor up or down if at end/start of line
o.startofline = true
o.laststatus = 3 -- global status line
o.foldenable = false -- all folds opened by default
o.foldmethod = "indent" -- make folds based on indent level
o.foldlevelstart = 99 -- don't close folds by default when opening buffer
o.iskeyword = o.iskeyword + "-" -- characters which are to be counted as 1 "word", added - for easily selecting variables e.g. foo-bar
o.spell = true -- Spellchecking
o.spelllang = "en"
o.listchars = "tab:→ ,space:·,nbsp:␣,trail:•,eol:↵,precedes:«,extends:»"
o.list = false
