output-file = ~/Downloads/%Y-%m-%d-%H%M%S.{ext}
# 0->9
png-compression-level = 4
# Move to the background when waiting for pastes after screenshotting.
move-to-background = true
# Backend preference for capturing outputs (monitors).
output-capture-backends = ext, wlr
# Copy the screenshot to the clipboard.
copy-to-clipboard = false
# Enable debug logging.
verbose = false

# This section is special: the options in here (except enabled) are consumed by an external
# process, so they cannot be overridden temporarily using the -C option.
[notify]
# Enable sending notifications.
enabled = true
# The notification summary.
summary = Screenshot saved
# The notification body when copy is enabled.
body-copy = Screenshot saved in <i>{{path}}</i> and copied to the clipboard.
# The notification body when copy is disabled.
body-nocopy = Screenshot saved in <i>{{path}}</i>.
# The command to invoke when the "Edit" button is clicked on a notification.
edit-command = satty --filename {{path}}
# The actions to put as buttons in the notification.
# open, edit, directory
actions = edit
# The action to use as default. 'none' for no action.
default-action = open

[region]
# 'smart' chooses a color based on how light the background is.
selection-border-color = smart
selection-border-width = 2px
background = "#10101099"
